name: node-process-env
on: workflow_dispatch
jobs:
  check-node-process-env:
    runs-on: ubuntu-latest
    steps:
      - run: node ./src/node-process-env.js
        env:
          HOST: 127.0.0.1
          PORT: 80
  
